# Generated by Django 2.1.3 on 2018-11-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuatrimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materias', models.ManyToManyField(to='jsonapi.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('aula', models.CharField(max_length=20)),
                ('grupo', models.IntegerField()),
                ('lun', models.TimeField()),
                ('mar', models.TimeField()),
                ('mier', models.TimeField()),
                ('jue', models.TimeField()),
                ('vie', models.TimeField()),
                ('sab', models.TimeField()),
                ('dom', models.TimeField()),
                ('modulo', models.IntegerField()),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Materia')),
            ],
        ),
    ]
