# Generated by Django 2.1.3 on 2018-11-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0002_cuatrimestre_horarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
    ]
