# Generated by Django 2.1.3 on 2018-11-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0004_auto_20181123_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='modulo',
        ),
    ]
