# Generated by Django 2.1.3 on 2018-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0005_remove_horario_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='modulo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
