# Generated by Django 2.1.3 on 2018-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0006_horario_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuatrimestre',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
