# Generated by Django 2.1.3 on 2018-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0007_cuatrimestre_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='jue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='lun',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='mar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='mier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='sab',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='vie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
